@url = http://localhost:4000/users

###
GET {{url}}
###

GET {{url}}/71
###

###
POST {{url}}
Content-Type: application/json

{
    "Codigo":71,
    "Nombre":"Jugo",
    "Precio":10.00,
    "Existencia":50
}

###
PUT {{url}}/71
Content-Type: application/json

{
    "Codigo":71,
    "Nombre":"Jugo",
    "Precio":10.00,
    "Existencia":80}

###
DELETE {{url}}/71
